-- MySQL Script generated by MySQL Workbench
-- Mon Aug 21 19:51:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Zapocet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Zapocet
-- -----------------------------------------------------
DROP DATABASE IF EXISTS Zapocet;
CREATE SCHEMA Zapocet DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

USE `Zapocet` ;

-- -----------------------------------------------------
-- Table `Zapocet`.`Authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zapocet`.`Authors` (
  `idAuthors` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Surename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idAuthors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zapocet`.`Genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zapocet`.`Genres` (
  `idgenr` INT NOT NULL AUTO_INCREMENT,
  `Genr_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idgenr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zapocet`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zapocet`.`Books` (
  `idbook` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `idAuthors` INT NOT NULL,
  `idgenr` INT NOT NULL,
  PRIMARY KEY (`idbook`),
  INDEX `Authors_idx` (`idAuthors` ASC) VISIBLE,
  INDEX `Genrs_idx` (`idgenr` ASC) VISIBLE,
  CONSTRAINT `Authors`
    FOREIGN KEY (`idAuthors`)
    REFERENCES `Zapocet`.`Authors` (`idAuthors`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Genrs`
    FOREIGN KEY (`idgenr`)
    REFERENCES `Zapocet`.`Genres` (`idgenr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zapocet`.`Readers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zapocet`.`Readers` (
  `idread` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Adress` VARCHAR(100) NOT NULL,
  `Surename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idread`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zapocet`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zapocet`.`staff` (
  `idstaff` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `surename` VARCHAR(100) NOT NULL,
  `pozition` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idstaff`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zapocet`.`Borrowers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zapocet`.`Borrowers` (
  `idborrow` INT NOT NULL AUTO_INCREMENT,
  `idreads` INT NOT NULL,
  `idbooks` INT NOT NULL,
  `borrew_date` DATETIME NOT NULL,
  `return_date` DATETIME NOT NULL,
  `idstaff` INT NOT NULL,
  PRIMARY KEY (`idborrow`),
  INDEX `readers_idx` (`idreads` ASC) VISIBLE,
  INDEX `books_idx` (`idbooks` ASC) VISIBLE,
  INDEX `staff-borrows_idx` (`idstaff` ASC) VISIBLE,
  CONSTRAINT `readers`
    FOREIGN KEY (`idreads`)
    REFERENCES `Zapocet`.`Readers` (`idread`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `books`
    FOREIGN KEY (`idbooks`)
    REFERENCES `Zapocet`.`Books` (`idbook`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `staff-borrows`
    FOREIGN KEY (`idstaff`)
    REFERENCES `Zapocet`.`staff` (`idstaff`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zapocet`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zapocet`.`Review` (
  `idrev` INT NOT NULL AUTO_INCREMENT,
  `idread` INT NOT NULL,
  `idbook` INT NOT NULL,
  `score` VARCHAR(100) NOT NULL,
  `coments` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idrev`),
  INDEX `readers_idx` (`idread` ASC) VISIBLE,
  INDEX `books_idx` (`idbook` ASC) VISIBLE,
  CONSTRAINT `readers_2`
    FOREIGN KEY (`idread`)
    REFERENCES `Zapocet`.`Readers` (`idread`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `books_2`
    FOREIGN KEY (`idbook`)
    REFERENCES `Zapocet`.`Books` (`idbook`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `Zapocet`.`Authors` (`Name`, `Surename`) VALUES
('John', 'Doe'),
('Jane', 'Smith'),
('Robert', 'Johnson'),
('Michael', 'Williams'),
('James', 'Brown'),
('David', 'Jones'),
('Richard', 'Garcia'),
('Joseph', 'Miller'),
('Charles', 'Davis'),
('Thomas', 'Rodriguez'),
('Christopher', 'Martinez'),
('Daniel', 'Hernandez'),
('Matthew', 'Lopez'),
('Donald', 'Gonzalez'),
('Anthony', 'Perez'),
('Mark', 'Wilson'),
('Paul', 'Anderson'),
('Steven', 'Taylor'),
('Andrew', 'Thomas'),
('Kenneth', 'White');

INSERT INTO `Zapocet`.`Genres` (`Genr_name`) VALUES
('Science fiction'),
('Fantasy'),
('Detective'),
('Novel'),
('Thriller'),
('Historical prose'),
('Biography'),
('Adventures'),
('Horror'),
('Drama'),
('Comedy'),
('Poetry'),
('Philosophy'),
('Popular Science'),
('Documental literature'),
('Children literature'),
('Satire'),
('Anthology'),
('Autobiography'),
('Memoirs');


INSERT INTO `Zapocet`.`Books` (`title`, `idAuthors`, `idgenr`) VALUES
('Space Odyssey', 1, 1),
('Dragon Tales', 2, 2),
('Whodunit Mystery', 3, 3),
('Love in the Air', 4, 4),
('Chills & Thrills', 5, 5),
('History of the Romans', 6, 6),
('Life of the Genius', 7, 7),
('Jungle Adventures', 8, 8),
('Nightmare Alley', 9, 9),
('Drama in Rain', 10, 10),
('Laugh Out Loud', 11, 11),
('Verses of the Heart', 12, 12),
('Thoughts & Reality', 13, 13),
('Secrets of the Universe', 14, 14),
('Behind the Scenes', 15, 15),
('Tales for Kids', 16, 16),
('The Satirical Times', 17, 17),
('Anthology of the Best', 18, 18),
('My Life, My Words', 19, 19),
('Memories of the Past', 20, 20);

INSERT INTO `Zapocet`.`Readers` (`Name`, `Adress`, `Surename`) VALUES
('Alice', '123 Wonderland St.', 'Turner'),
('Bob', '456 Evergreen Terrace', 'Smith'),
('Charlie', '789 Choco Factory', 'Brown'),
('David', '101 Maple Street', 'Harris'),
('Eva', '202 Riverside Drive', 'Garcia'),
('Frank', '303 Sunset Blvd', 'Williams'),
('Grace', '404 Moonlit Lane', 'Robinson'),
('Henry', '505 Starry Avenue', 'Johnson'),
('Isabelle', '606 Rainbow Road', 'Jones'),
('Jack', '707 Palm Tree Court', 'White'),
('Katherine', '808 Snowflake Pass', 'Moore'),
('Liam', '909 Mountain Peak', 'Martin'),
('Monica', '110 Ocean View', 'Martinez'),
('Nathan', '212 Forest Trail', 'Thompson'),
('Olivia', '313 Sunny Meadows', 'Taylor'),
('Peter', '414 Mystic Falls', 'Davis'),
('Quinn', '515 Dreamy Dale', 'Rodriguez'),
('Rachel', '616 Whispering Pines', 'Gonzalez'),
('Steve', '717 Golden Sands', 'Perez'),
('Tiffany', '818 Starlight Drive', 'Clark');

INSERT INTO `Zapocet`.`staff` (`Name`, `surename`, `pozition`) VALUES
('John', 'Doe', 'Librarian'),
('Anna', 'Smith', 'Assistant Librarian'),
('Edward', 'Johnson', 'Archivist'),
('Claire', 'Williams', 'Book Curator'),
('Benjamin', 'Jones', 'Maintenance'),
('Emily', 'Brown', 'Event Coordinator'),
('Nicholas', 'Davis', 'Tech Support'),
('Rebecca', 'Miller', 'Librarian'),
('Samuel', 'Garcia', 'Children’s Librarian'),
('Julia', 'Rodriguez', 'Receptionist'),
('Victor', 'Martinez', 'IT Specialist'),
('Sophie', 'Hernandez', 'Security'),
('Lawrence', 'Moore', 'Book Restorer'),
('Danielle', 'Wilson', 'Research Assistant'),
('Philip', 'Taylor', 'Librarian'),
('Alicia', 'Anderson', 'Library Marketing'),
('Gerald', 'Thomas', 'Inventory Manager'),
('Eleanor', 'Hall', 'Outreach Coordinator'),
('Freddie', 'Turner', 'Assistant Librarian'),
('Megan', 'Jackson', 'Public Relations');

INSERT INTO `Zapocet`.`Borrowers` (`idreads`, `idbooks`, `borrew_date`, `return_date`, `idstaff`) VALUES
(1, 1, CURDATE() - INTERVAL 20 DAY, CURDATE() - INTERVAL 6 DAY, 1),
(2, 2, CURDATE() - INTERVAL 19 DAY, CURDATE() - INTERVAL 5 DAY, 2),
(3, 3, CURDATE() - INTERVAL 18 DAY, CURDATE() - INTERVAL 4 DAY, 3),
(4, 4, CURDATE() - INTERVAL 17 DAY, CURDATE() - INTERVAL 3 DAY, 4),
(5, 5, CURDATE() - INTERVAL 16 DAY, CURDATE() - INTERVAL 2 DAY, 5),
(6, 6, CURDATE() - INTERVAL 15 DAY, CURDATE() - INTERVAL 1 DAY, 6),
(7, 7, CURDATE() - INTERVAL 14 DAY, CURDATE(), 7),
(8, 8, CURDATE() - INTERVAL 13 DAY, CURDATE() + INTERVAL 1 DAY, 8),
(9, 9, CURDATE() - INTERVAL 12 DAY, CURDATE() + INTERVAL 2 DAY, 9),
(10, 10, CURDATE() - INTERVAL 11 DAY, CURDATE() + INTERVAL 3 DAY, 10),
(11, 11, CURDATE() - INTERVAL 10 DAY, CURDATE() + INTERVAL 4 DAY, 11),
(12, 12, CURDATE() - INTERVAL 9 DAY, CURDATE() + INTERVAL 5 DAY, 12),
(13, 13, CURDATE() - INTERVAL 8 DAY, CURDATE() + INTERVAL 6 DAY, 13),
(14, 14, CURDATE() - INTERVAL 7 DAY, CURDATE() + INTERVAL 7 DAY, 14),
(15, 15, CURDATE() - INTERVAL 6 DAY, CURDATE() + INTERVAL 8 DAY, 15),
(16, 16, CURDATE() - INTERVAL 5 DAY, CURDATE() + INTERVAL 9 DAY, 16),
(17, 17, CURDATE() - INTERVAL 4 DAY, CURDATE() + INTERVAL 10 DAY, 17),
(18, 18, CURDATE() - INTERVAL 3 DAY, CURDATE() + INTERVAL 11 DAY, 18),
(19, 19, CURDATE() - INTERVAL 2 DAY, CURDATE() + INTERVAL 12 DAY, 19),
(20, 20, CURDATE() - INTERVAL 1 DAY, CURDATE() + INTERVAL 13 DAY, 20);

INSERT INTO `Zapocet`.`Review` (`idread`, `idbook`, `score`, `coments`) VALUES
(1, 1, 'Excellent', 'Thoroughly enjoyed this book. A must-read!'),
(2, 2, 'Good', 'A good read, though it had some slow parts.'),
(3, 3, 'Average', 'Decent story, but it lacked depth in some areas.'),
(4, 4, 'Below Average', 'Struggled to keep my interest.'),
(5, 5, 'Poor', 'Not my cup of tea. Found it very hard to finish.'),
(6, 6, 'Excellent', 'Absolutely captivating from start to finish!'),
(7, 7, 'Good', 'Worth a read, especially for fans of the genre.'),
(8, 8, 'Average', 'An okay book, nothing groundbreaking.'),
(9, 9, 'Good', 'Had some brilliant moments, but felt dragged in a few sections.'),
(10, 10, 'Excellent', 'Highly recommend this one. Great character development!'),
(11, 11, 'Average', 'A decent one-time read. Probably won’t revisit.'),
(12, 12, 'Good', 'I enjoyed the plot twists, but the ending was predictable.'),
(13, 13, 'Poor', 'Couldn’t relate to the characters at all.'),
(14, 14, 'Below Average', 'The narrative felt disjointed. Not a fan.'),
(15, 15, 'Good', 'The setting was vividly described. Enjoyed the world-building.'),
(16, 16, 'Excellent', 'Kept me on the edge of my seat. A roller-coaster of emotions.'),
(17, 17, 'Average', 'It’s a quick read. Nothing too memorable.'),
(18, 18, 'Below Average', 'Expected more from the story. It felt incomplete.'),
(19, 19, 'Poor', 'The writing style was not to my taste.'),
(20, 20, 'Excellent', 'A delightful read! Can’t wait for the sequel.');

SELECT r.idread, r.Name, r.Surename, COUNT(*) AS number_of_books_borrowed
FROM `Zapocet`.`Readers` r
INNER JOIN `Zapocet`.`Borrowers` b ON r.idread = b.idreads
GROUP BY r.idread, r.Name, r.Surename
HAVING COUNT(*) > 0;

SELECT b.title, g.Genr_name, a.Name AS author_name, a.Surename AS author_surename
FROM `Zapocet`.`Books` b
INNER JOIN `Zapocet`.`Genres` g ON b.idgenr = g.idgenr
INNER JOIN `Zapocet`.`Authors` a ON b.idAuthors = a.idAuthors
ORDER BY g.Genr_name;

CREATE VIEW `Zapocet`.`ReaderStats` AS
SELECT r.Name, r.Surename, COUNT(DISTINCT b.idborrow) AS borrowed_books, COUNT(DISTINCT rev.idrev) AS reviews_written
FROM `Zapocet`.`Readers` r
LEFT JOIN `Zapocet`.`Borrowers` b ON r.idread = b.idreads
LEFT JOIN `Zapocet`.`Review` rev ON r.idread = rev.idread
GROUP BY r.idread, r.Name, r.Surename; 
SELECT * FROM `Zapocet`.`ReaderStats`;



SELECT s.Name, s.surename, COUNT(*) AS transactions_processed
FROM `Zapocet`.`staff` s
INNER JOIN `Zapocet`.`Borrowers` b ON s.idstaff = b.idstaff
GROUP BY s.idstaff, s.Name, s.surename
HAVING COUNT(*) > 0;
